# Generated by Django 5.0.7 on 2024-07-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_admin_adminid_alter_employees_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
