# Generated by Django 5.0.7 on 2024-07-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_employees_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
