# Generated by Django 5.0.7 on 2024-07-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_hrleavestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='hrmonthleavestatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leaves', models.IntegerField(verbose_name='')),
                ('sick_leaves', models.IntegerField(verbose_name='')),
                ('half_day_leaves', models.IntegerField(verbose_name='')),
            ],
        ),
    ]
