# Generated by Django 5.0.7 on 2024-07-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_hrmonthleavestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmonthleavestatus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
