# Generated by Django 5.0.7 on 2024-07-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_alter_hrmonthleavestatus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestatus',
            name='excess_leave',
            field=models.IntegerField(default=1, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavestatusmonth',
            name='excess_leave',
            field=models.IntegerField(default=1, verbose_name=''),
            preserve_default=False,
        ),
    ]
