from django.urls import path
from guest import views

urlpatterns = [
    path('login',views.login,name="login"),
    path('addemployee',views.addemployee,name="addemployee"),
    path('addemployee/<id>',views.addemployee,name="addemployee"),
    path('getcount',views.getcount,name="getcount"),
    path('getdate',views.getdate,name="getdate"),
    path('addbonus',views.addbonus,name="addbonus"),
    path('editform/<id>',views.editform,name="editform"),
    path('getemployee',views.getemployee,name="getemployee"),
    path('getemployeebyid/<id>',views.getemployeebyid,name="getemployeebyid"),
    path('submitleave',views.submitleave,name="submitleave"),
    path('getleavestatusbyid/<id>',views.getleavestatusbyid,name="getleavestatusbyid"),
    path('deleteleave/<id>',views.deleteleave,name="deleteleave"),
    path('getcountofleavereq',views.getcountofleavereq,name="getcountofleavereq"),
    path('approveleave/<emp_id>/<leave_id>',views.approveleave,name="approveleave"),
    path('generatesalary',views.generatesalary,name="generatesalary"),
    path('viewsalary',views.viewsalary,name="viewsalary"),
    path('proceedsalary/<id>',views.proceedsalary,name="proceedsalary"),
    path('viewsalarygenerated',views.viewsalarygenerated,name="viewsalarygenerated"),
    path('getsalarybyid/<id>',views.getsalarybyid,name="getsalarybyid"),
    path('getleavebyid/<id>',views.getleavebyid,name="getleavebyid"),
    path('forgetpassword',views.forgetpassword,name="forgetpassword"),
    path('changepassword',views.changepassword,name="changepassword"),
    path('generatesalaryforthismonth/<id>',views.generatesalaryforthismonth,name="generatesalaryforthismonth"),
    path('viewsalaryforthismonth/<id>',views.viewsalaryforthismonth,name="viewsalaryforthismonth"),
    path('getbonusbyid/<id>',views.getbonusbyid,name="getbonusbyid"),
    path('getdeductionbyid/<id>',views.getdeductionbyid,name="getdeductionbyid"),
    path('getotherdeductionbyid/<id>',views.getotherdeductionbyid,name="getotherdeductionbyid"),
    path('getallbonus',views.getallbonus,name="getallbonus"),
    path('getalldeductions',views.getalldeductions,name="getalldeductions"),
    path('getallotherdeductions',views.getallotherdeductions,name="getallotherdeductions"),
    path('gethalfday/<id>',views.gethalfday,name="gethalfday"),
    path('getstatusmonthbyid/<id>',views.getstatusmonthbyid,name="getstatusmonthbyid"),
    path('updatestatusinleavemonth/<id>',views.updatestatusinleavemonth,name="updatestatusinleavemonth"),
    path('leavemonth/<emp_id>/<leave_id>',views.leavemonth,name="leavemonth"),
    path('deletesalary/<id>',views.deletesalary,name="deletesalary"),
    path('proceedsalaryformonth/<id>',views.proceedsalaryformonth,name="proceedsalaryformonth"),
    path('viewsalarymonth',views.viewsalarymonth,name="viewsalarymonth"),
    path('getsalarymonthbyid/<id>',views.getsalarymonthbyid,name="getsalarymonthbyid"),
    path('deletesalaryall/<id>',views.deletesalaryall,name="deletesalaryall"),
    path('otp_list',views.otp_list,name="otp"),
    path('clearotp/<id>',views.clearotp,name="clearotp"),
    path('gethrleave',views.gethrleave,name="gethrleave"),
    path('updateleaveall/<id>',views.updateleaveall,name="updateleaveall"),
    path('hrleaveget',views.hrleaveget,name="hrleaveget"),
    path('hrmonthleave',views.hrmonthleave,name="hrmonthleave"),
    path('updatemonthleave/<id>',views.updatemonthleave,name="updatemonthleave")
    
]
